### ISSUE TITLE
Request for the fine-tuned BERT model (BertForTokenClassification)

### ISSUE THREAD

**Issue by suzisuti** [SIKU-BERT/sikufenci#1]
```该文件可以通过如下的百度云链接下载: 链接：https://pan.baidu.com/s/1ePPlCpoZ4UTsUaQumMpZTQ 提取码：c9hb```

Hello, thanks for sharing your library.
Unfortunately, I can't download your `pytorch_model.bin` in Baidu because I don't have a Chinese mobile phone number, which prohibits me from signing in to Baidu.

I guess the BERT model you've uploaded in Baidu is a fine-tuned version for word tokenization (an instance of BertForTokenClassification), and it's different from the one in `https://huggingface.co/SIKU-BERT/sikubert` (an instance of BertForMaskedLM), isn't it?

I wonder if you have a plan to upload the fine-tuned model via HuggingFace. Thanks.

**Comment by SIKU-BERT** [comment]
Dear  suzisuti,
Our fine-tuned model has been shared using Google drive,and the link has been updated in ReadME. Now non-Chinese users can download it using Google drive.Thank you for your attention to our project.

**Comment by suparklingmin** [comment]
Thank you very much and happy new year!

**Comment by SIKU-BERT** [comment]
It is a pleasure. Wish you a happy new year.
